#!/usr/bin/env node
// Generate closed-alpha invite codes and print the SQL that inserts them into
// the "invite_code" table (migration 0006). It does NOT touch the database
// itself — it prints SQL so you decide where it runs (local or --remote) and
// can eyeball it first.
//
// Usage:
//   node scripts/invite/create-invite.mjs [options]
//
// Options:
//   --count N     how many codes to generate            (default 1)
//   --uses N      accounts each code may create          (default 1)
//   --days N      code expires N days from now           (default: never)
//   --note "..."  reminder stored with the code(s)       (default: none)
//   --prefix STR  code prefix                            (default FJELL)
//
// Examples:
//   # Five single-use codes for the first testers:
//   node scripts/invite/create-invite.mjs --count 5 --note "batch-1"
//
//   # One shared code, 30 uses, expires in 14 days:
//   node scripts/invite/create-invite.mjs --uses 30 --days 14 --note "ski club"
//
// Apply the printed SQL to the production D1 database:
//   node scripts/invite/create-invite.mjs --count 5 > /tmp/codes.sql
//   npx wrangler d1 execute fjellrute-db --remote --file /tmp/codes.sql
// (drop --remote and use --local to seed a local dev database instead.)

import { randomBytes } from 'node:crypto';

// Uniform index into an alphabet of length `max` using rejection sampling on
// random bytes, so there's no modulo bias. (Avoids crypto.randomInt / the ??
// operator so the script also runs on older Node.)
function randomIndex(max) {
  const limit = 256 - (256 % max);
  let byte;
  do {
    byte = randomBytes(1)[0];
  } while (byte >= limit);
  return byte % max;
}

function parseArgs(argv) {
  const out = { count: 1, uses: 1, days: null, note: null, prefix: 'FJELL' };
  for (let i = 0; i < argv.length; i += 1) {
    const key = argv[i];
    const val = argv[i + 1];
    switch (key) {
      case '--count':
        out.count = Number(val);
        i += 1;
        break;
      case '--uses':
        out.uses = Number(val);
        i += 1;
        break;
      case '--days':
        out.days = Number(val);
        i += 1;
        break;
      case '--note':
        out.note = val;
        i += 1;
        break;
      case '--prefix':
        out.prefix = String(val).toUpperCase();
        i += 1;
        break;
      default:
        throw new Error(`Unknown option: ${key}`);
    }
  }
  if (!Number.isInteger(out.count) || out.count < 1)
    throw new Error('--count must be a positive integer');
  if (!Number.isInteger(out.uses) || out.uses < 1)
    throw new Error('--uses must be a positive integer');
  if (out.days !== null && (!Number.isFinite(out.days) || out.days <= 0))
    throw new Error('--days must be a positive number');
  return out;
}

// Unambiguous alphabet: no 0/O/1/I/L so codes are easy to read out and type.
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

function group(n) {
  let s = '';
  for (let i = 0; i < n; i += 1) s += ALPHABET[randomIndex(ALPHABET.length)];
  return s;
}

function makeCode(prefix) {
  // PREFIX-XXXX-XXXX → 8 random chars from a 31-char set ≈ 40 bits of entropy,
  // far beyond what the per-IP rate limit (15/hour) lets anyone guess.
  return `${prefix}-${group(4)}-${group(4)}`;
}

// SQL string literal: single quotes doubled, wrapped; null stays NULL.
function sql(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  const expiresAt =
    opts.days === null
      ? null
      : new Date(Date.now() + opts.days * 86400000).toISOString();

  const codes = new Set();
  while (codes.size < opts.count) codes.add(makeCode(opts.prefix));

  const lines = [
    '-- Generated by scripts/invite/create-invite.mjs',
    `-- ${new Date().toISOString()}  (uses=${opts.uses}, expires=${
      expiresAt || 'never'
    }, note=${opts.note || 'none'})`,
  ];
  for (const code of codes) {
    lines.push(
      'INSERT INTO "invite_code" ' +
        '("code","note","max_uses","expires_at") VALUES (' +
        `${sql(code)}, ${sql(opts.note)}, ${opts.uses}, ${sql(expiresAt)});`,
    );
  }

  // The codes themselves go to stderr so that `> codes.sql` captures only the
  // SQL, while you still see the human-readable list in the terminal.
  console.error('\nGenerated invite codes:');
  for (const code of codes) console.error(`  ${code}`);
  console.error('');

  console.log(lines.join('\n'));
}

main();
